# Site settings
title: JEP-APP
email:
description: A jekyll template for landing pages, portfolio and blogging

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "http://app.jprefer.com" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
# data-ad-slot: 
# data-ad-client: 
# google_ad_client: 

google_analytics: "UA-2914412-12"
# addthis_id: 
# disqus_account: 

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/jprefer
  - title: facebook
    url: https://facebook.com/jprefer
  - title: google-plus
    url: https://plus.google.com/jprefer
  - title: github
    url: http://github.com/jprefer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings

plugins:
  - jekyll-sitemap
